<?php
// VC [mgt_images_slider_wp]
vc_map(array(
   "name" 			=> "MGT Images Slider and Carousel",
   "category" 		=> 'CryptiBIT Content',
   "description"	=> "Powerful images gallery/slider/carousel",
   "base" 			=> "mgt_images_slider_wp",
   "class" 			=> "",
   "icon" 			=> "vc_mgt_images_slider",
   "params" 	=> array(
   		array(
			"type"			=> "mgt_separator",
			"param_name"	=> generate_separator_name(),
			"heading"		=> "Slider images settings",
		),
		array(
			"type"			=> "attach_images",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Slider images",
			"param_name"	=> "slider_images",
			"description"	=> "Select your slider images.",
			"std"			=> "",
		),
		array(
			"type"			=> "textfield",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> true,
			"heading"		=> "Image size",
			"description"	=> 'Enter image size. Example: thumbnail, medium, large, full or other sizes defined by current theme. Alternatively enter image size in pixels: 200x100 (Width x Height). Leave empty to use "full" size. If used slides per view, this will be used to define carousel wrapper size.',
			"param_name"	=> "slider_image_size",
			"std"			=> "",
		),
		array(
			"type"			=> "mgt_separator",
			"param_name"	=> generate_separator_name(),
			"heading"		=> "Slider settings",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Infinity slider",
			"param_name"	=> "infinite",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "true",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Slider scroll direction",
			"param_name"	=> "vertical",
			"value"			=> array(
				"Horizontal"	=> "false",
				"Vertical"	=> "true"
			),
			"description"	=> "",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Slider autoplay",
			"param_name"	=> "autoplay",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "true",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "textfield",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> true,
			"heading"		=> "Slider autoplay speed (msec)",
			"description"	=> 'For example: 3000 (for 3 seconds)',
			"param_name"	=> "autoplay_speed",
			"std"			=> "3000",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Slider animation",
			"param_name"	=> "fade",
			"value"			=> array(
				"Scroll"	=> "false",
				"Fade"	=> "true"
			),
			"description"	=> "Fade effect will work correctly if you use 1 image per slide/row. Does not work for galleries with multiple images in a row.",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "textfield",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> true,
			"heading"		=> "Slider animation speed (msec)",
			"description"	=> 'For example: 300 (for 0.3 seconds)',
			"param_name"	=> "speed",
			"std"			=> "300",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "textfield",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> true,
			"heading"		=> "Slider images per row",
			"description"	=> '',
			"param_name"	=> "slides",
			"std"			=> "1",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "textfield",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> true,
			"heading"		=> "Slider images move per scroll",
			"description"	=> '',
			"param_name"	=> "slidesscroll",
			"std"			=> "1",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Show arrows",
			"param_name"	=> "arrows",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "true",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Show pagination",
			"param_name"	=> "dots",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "true",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Center and zoom active slide",
			"param_name"	=> "centeractiveslide",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "Active slider on center will be zoomed.",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "textfield",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> true,
			"heading"		=> "Side padding for centered slide",
			"description"	=> 'Side padding when in center mode (px or %). For example: 60px',
			"param_name"	=> "center_padding",
			"std"			=> "60px",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Variable width",
			"param_name"	=> "variable_width",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Adaptive height",
			"param_name"	=> "adaptive_height",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Space between images",
			"param_name"	=> "slider_padding",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "dropdown",
			"holder"		=> "div",
			"class" 		=> "hide_in_vc_editor",
			"admin_label" 	=> false,
			"heading"		=> "Add link to bigger image for images",
			"param_name"	=> "slider_lightbox",
			"value"			=> array(
				"Yes"	=> "true",
				"No"	=> "false"
			),
			"description"	=> "",
			"std"			=> "false",
			"edit_field_class" => "vc_col-xs-6",
		),
		array(
			"type"			=> "mgt_separator",
			"param_name"	=> generate_separator_name(),
			"heading"		=> "Animation and effects",
		),
		// CSS Animations
		vc_map_add_css_animation( true ),

   )

));
